### ISSUE TITLE
Gimple Gallery not running in DNN 9.2.0

### ISSUE THREAD

**Issue by TobiLanger** [ventrian/Simple-Gallery#1]
Hi,

after upgrading to DNN 9.2.0 Simple-Gallery is not running any more.
I think its the same problem like in ventrians news-articles module.
[Please find this issue](https://github.com/ventrian/News-Articles/issues/6)

I get the following in the log:
`Message:Methode nicht gefunden: "System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()".
StackTrace:
InnerMessage:Methode nicht gefunden: "System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()".
InnerStackTrace:
bei Ventrian.SimpleGallery.SimpleGalleryBase.HasEditPermissions() bei Ventrian.SimpleGallery.Controls.GalleryMenu.AssignLinks() bei Ventrian.SimpleGallery.Controls.GalleryMenu.Page_Load(Object sender, EventArgs e)`

Could somebody help?

Thanks, Tobias Langer

**Comment by Timo-Breumelhof** [comment]
Try the new release :-)

**Comment by TobiLanger** [comment]
Oh thank you, works great !!!
